name: android_gesture_exclusion_example
description: Demonstrates how to use the android_gesture_exclusion plugin.

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  android_gesture_exclusion:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
