name: android_gesture_exclusion_example
description: Demonstrates how to use the android_gesture_exclusion plugin.

environment:
  sdk: '<4.0.0'

dependencies:
  flutter:
    sdk: flutter

  android_gesture_exclusion:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.2
