name: android_gesture_exclusion_platform_interface
description: A common platform interface for the android_gesture_exclusion plugin. Different platform implementations of android_gesture_exclusion should implement this interface.
version: 0.2.0
homepage: https://github.com/b4tchkn/android_gesture_exclusion/tree/main/android_gesture_exclusion_platform_interface
repository: https://github.com/b4tchkn/android_gesture_exclusion/tree/main/android_gesture_exclusion_platform_interface
documentation: https://github.com/b4tchkn/android_gesture_exclusion/tree/main/android_gesture_exclusion_platform_interface
issue_tracker: https://github.com/b4tchkn/android_gesture_exclusion/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
