name: android_gesture_exclusion_platform_interface
description: A common platform interface for the android gesture exclude plugin.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: 2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.1
