name: android_gesture_exclusion
description: Flutter plugin to exclude android gesture navigation.
version: 0.2.1
homepage: https://github.com/b4tchkn/android_gesture_exclusion/tree/main/android_gesture_exclusion
repository: https://github.com/b4tchkn/android_gesture_exclusion/tree/main/android_gesture_exclusion
documentation: https://github.com/b4tchkn/android_gesture_exclusion/tree/main/android_gesture_exclusion
issue_tracker: https://github.com/b4tchkn/android_gesture_exclusion/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: ^0.4.0+2
  android_gesture_exclusion_platform_interface: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.github.b4tchkn.android_gesture_exclusion
        pluginClass: AndroidGestureExclusionPlugin
