name: android_gesture_exclusion
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/b4tchkn/android_gesture_exclusion
repository: https://github.com/b4tchkn/android_gesture_exclusion
documentation: https://github.com/b4tchkn/android_gesture_exclusion
issue_tracker: https://github.com/b4tchkn/android_gesture_exclusion/issues

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  visibility_detector: 0.3.3
  android_gesture_exclusion_platform_interface:
    path: ../android_gesture_exclusion_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.github.b4tchkn.android_gesture_exclusion
        pluginClass: AndroidGestureExclusionPlugin
